### ISSUE TITLE
Adjust author name in titleStmt

### ISSUE THREAD

**Issue by peertrilcke** [dracor-org/eco_en#4]
> When used within a [<titleStmt>], an author's name is given in a standardized format (surname, forename/s, (YYYY-YYYY)) as shown in this example.
> `<author ref="viaf:31996364">Forster, Edward Morgan (1879-1970)</author>`

https://distantreading.github.io/Schema/eltec-1.html#TEI.author

**Comment by DanilSko** [comment]
Done, see here: https://github.com/dracor-org/eco_en/commit/7773d8a468c7ce5be74eaf61bbb22f6505a78482  and here: https://github.com/dracor-org/eco_de/commit/fece937762e5ddc44e9aeb23fd4a6ec051e3e96e
